from django.contrib import admin
from hang.models import *

admin.site.register(Hanger)
admin.site.register(Str_Hanger)
admin.site.register(IntegerField_Hanger)
admin.site.register(BooleanField_Hanger)
admin.site.register(EmailField_Hanger)
admin.site.register(BigIntegerField_Hanger)
admin.site.register(CharField_Hanger)
admin.site.register(CommaSeparatedIntegerField_Hanger)
admin.site.register(DateField_Hanger)
admin.site.register(DateTimeField_Hanger)
admin.site.register(DecimalField_Hanger)
admin.site.register(FileField_Hanger)
admin.site.register(FilePathField_Hanger)
admin.site.register(FloatField_Hanger)
admin.site.register(ImageField_Hanger)
admin.site.register(IPAddressField_Hanger)
admin.site.register(GenericIPAddressField_Hanger)
admin.site.register(NullBooleanField_Hanger)
admin.site.register(PositiveIntegerField_Hanger)
admin.site.register(PositiveSmallIntegerField_Hanger)
admin.site.register(SlugField_Hanger)
admin.site.register(SmallIntegerField_Hanger)
admin.site.register(TextField_Hanger)
admin.site.register(URLField_Hanger)
admin.site.register(ForeignKey_Hanger)
admin.site.register(ManyToManyField_Hanger)
admin.site.register(OneToOneField_Hanger)

# admin.site.register()